<?php

namespace Ballack\TimeSheetBundle\Repository;
use Ballack\TimeSheetBundle\Entity\Employe;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyProjets(Employe $employe){

    }
}
