<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * TypeAbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAbsenceRepository extends \Doctrine\ORM\EntityRepository
{
}
