dayferiee_index:
    path:     /
    defaults: { _controller: "BallackTimeSheetBundle:DayFeriee:index" }
    methods:  GET

dayferiee_show:
    path:     /{id}/show
    defaults: { _controller: "BallackTimeSheetBundle:DayFeriee:show" }
    methods:  GET

dayferiee_new:
    path:     /new
    defaults: { _controller: "BallackTimeSheetBundle:DayFeriee:new" }
    methods:  [GET, POST]

dayferiee_edit:
    path:     /{id}/edit
    defaults: { _controller: "BallackTimeSheetBundle:DayFeriee:edit" }
    methods:  [GET, POST]

dayferiee_delete:
    path:     /{id}/delete
    defaults: { _controller: "BallackTimeSheetBundle:DayFeriee:delete" }
    methods:  DELETE
