absence_index:
    path:     /
    defaults: { _controller: "BallackTimeSheetBundle:Absence:index" }
    methods:  GET

absence_show:
    path:     /{id}/show
    defaults: { _controller: "BallackTimeSheetBundle:Absence:show" }
    methods:  GET

absence_new:
    path:     /new
    defaults: { _controller: "BallackTimeSheetBundle:Absence:new" }
    methods:  [GET, POST]

absence_edit:
    path:     /{id}/edit
    defaults: { _controller: "BallackTimeSheetBundle:Absence:edit" }
    methods:  [GET, POST]

absence_delete:
    path:     /{id}/delete
    defaults: { _controller: "BallackTimeSheetBundle:Absence:delete" }
    methods:  DELETE

