services:
#    ballack_time_sheet.example:
#        class: Ballack\TimeSheetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#      ballack_time_sheet.locale_listener:
#        class: Ballack\TimeSheetBundle\EventListener\LocaleListener
#        arguments: ["%kernel.default_locale%"]
#        tags:
#          - { name: kernel.event_subscriber }
#          - { name: kernel.event_listener, event: security.authentication.success, method: onLogin }
#      ballack_time_sheet.user.login:
#              class: Ballack\TimeSheetBundle\EventListener\LoginListener
#              arguments: [@security.context, @router]
#              tags:
#                  - { name: kernel.event_listener, event: security.authentication.success, method: handle }
#                  - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
#      ballack_time_sheet.security.interactive_login_listener:
#            class: Ballack\TimeSheetBundle\EventListener\UserLocaleListener
#            calls:
#              - [ setSession, [@session] ]
#            tags:
#              - { name: kernel.event_listener, event: security.interactive_login, method: setLocaleForAuthenticatedUser }