<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * EmployeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findChefDepartement($departement)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.isChef = :chef')
            ->setParameter('chef', true)
            ->andWhere('a.departement = :depa')
            ->setParameter('depa', $departement)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
