<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * TypeContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeContratRepository extends \Doctrine\ORM\EntityRepository
{
}
