security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CHEF:        [ROLE_USER]
        ROLE_ADMIN:       [ROLE_USER,ROLE_CHEF]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: true
#        login:
#            pattern: ^/(login|register|resetting) # Les adresses de ces pages sont login, register et resetting
#            anonymous: false
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle      # On lit l'authentification au provider définit plus haut
                login_path: /login
                use_forward: false
                failure_path: null
                default_target_path: /
                remember_me: true # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
            remember_me:
                key: %secret% # On définit la clé pour le remember_me (%secret% est un parametre de parameters.ini)
            anonymous: true # On autorise les utilisateurs anonymes (non identifiés)
            logout: 
              path: /logout
              target: /
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_ANONYMOUSLY }
                

