employe_index:
    path:     /
    defaults: { _controller: "BallackTimeSheetBundle:Employe:index" }
    methods:  GET

employe_show:
    path:     /{id}/show
    defaults: { _controller: "BallackTimeSheetBundle:Employe:show" }
    methods:  GET

employe_new:
    path:     /new
    defaults: { _controller: "BallackTimeSheetBundle:Employe:new" }
    methods:  [GET, POST]

employe_edit:
    path:     /{id}/edit
    defaults: { _controller: "BallackTimeSheetBundle:Employe:edit" }
    methods:  [GET, POST]

employe_delete:
    path:     /{id}/delete
    defaults: { _controller: "BallackTimeSheetBundle:Employe:delete" }
    methods:  DELETE
employe_search:
    path:     /search
    defaults: { _controller: "BallackTimeSheetBundle:Employe:search" }
    methods:  GET
employe_role:
    path:     /{id}/role
    defaults: { _controller: "BallackTimeSheetBundle:Employe:role" }
    methods:  [GET]
employe_deleteRole:
  pattern: /{id}/{role}/
  defaults: { _controller: BallackTimeSheetBundle:Employe:deleteRole}
employe_addRole:
  pattern: /{id}/{role}/add
  defaults: { _controller: BallackTimeSheetBundle:Employe:addRole}
  methods:  [GET, POST]
employe_profil:
    path:     /profil
    defaults: { _controller: "BallackTimeSheetBundle:Employe:profil" }
    methods:  [GET]