overtime_index:
    path:     /
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:index" }
    methods:  GET

overtime_show:
    path:     /{id}/show
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:show" }
    methods:  GET

overtime_new:
    path:     /new
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:new" }
    methods:  [GET, POST]

overtime_edit:
    path:     /{id}/edit
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:edit" }
    methods:  [GET, POST]

overtime_delete:
    path:     /{id}/delete
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:delete" }
    methods:  DELETE

overtime_my:
    path:     /mesovertime
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:mesOvertime" }
    methods:  GET

overtime_validation:
    path:     /validation
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:validation_overtime" }
    methods:  GET
overtime_ok:
    path:     /{id}/ok
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:validation_Ok" }
    methods:  [GET, POST]

overtime_nonOk:
    path:     /{id}/nonOk
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:validation_NonOk" }
    methods:  [GET, POST]

overtime_attente:
    path:     /{id}/attente
    defaults: { _controller: "BallackTimeSheetBundle:OverTime:validation_Attente" }
    methods:  [GET, POST]