<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAbsencebyNotValidByDepartement($departement)
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.employe', 'e')
            ->addSelect('e')
/*            ->andWhere('a.statutChef = :statutChef')
            ->setParameter('statutChef', "attente")
            ->orWhere('a.statut = :statut')
            ->setParameter('statut', "attente")*/
            ->andWhere('e.departement = :depa')
            ->setParameter('depa', $departement)
            ->getQuery()
            ->execute();
    }
    public function findAllAbsenceByDepartement()
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.employe', 'e')
            ->addSelect('e')
           /* ->andWhere('a.statutChef = :statutChef')
            ->setParameter('statutChef',"accepte")*/
            ->addOrderBy('a.statutChef')
            ->getQuery()
            ->execute();
    }
    public function findAllAbsencebyNotValidByDepartementDQL()
    {
        $query = $this->_em->createQuery('SELECT a FROM BallackTimeSheetBundle:Absence a where');
        $resultats = $query->getResult();

        return $resultats;
    }
}
