<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * OverTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OverTimeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOvertimeByDepartement($departement)
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.employe', 'e')
            ->addSelect('e')
            ->andWhere('e.departement = :depa')
            ->setParameter('depa', $departement)
            ->addOrderBy('a.date','desc')
            ->getQuery()
            ->execute();
    }
}
