<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActivitebyEmployeByProjet($emp,$projet)
    {
        return $this->createQueryBuilder('a')
             ->andWhere('a.employe = :employe')
            ->setParameter('employe', $emp)
            ->andWhere('a.projet = :projet')
            ->setParameter('projet', $projet)
            ->getQuery()
            ->execute();
    }
    public function findAllActiviteByProjet($projet)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.projet = :projet')
            ->setParameter('projet', $projet)
            ->getQuery()
            ->execute();
    }
}
