<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * DayFerieeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayFerieeRepository extends \Doctrine\ORM\EntityRepository
{
}
