<?php

namespace Ballack\TimeSheetBundle\Repository;

/**
 * OverTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OverTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
